# Eat Safe, Love

## Notebook Set Up

In [98]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [99]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [100]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [101]:
# review the collections in our database
collections = db.list_collection_names()
pprint(collections)

['establishments']

In [102]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [103]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}

result_1 = establishments.find(query)

# Use count_documents to display the number of documents in the result
print('Number of establishments with a hygiene score of 20: ', establishments.count_documents(query))

# Retrieve the results
pprint(result_1[0])

Number of establishments with a hygiene score of 20:  41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6778b6b955335ff7f287d8da'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('0.27694')},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [104]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.DataFrame(result_1)

# Display the number of rows in the DataFrame
print('Number of rows in dataframe: ', len(hygiene_df))

# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

Number of rows in dataframe:  41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,latitude,longitude
0,6778b6b955335ff7f287d8da,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,6778b6ba55335ff7f287dc5b,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,6778b6ba55335ff7f287df65,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,6778b6ba55335ff7f287e153,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,6778b6ba55335ff7f287e162,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
5,6778b6bb55335ff7f287eb01,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
6,6778b6bb55335ff7f287ed22,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
7,6778b6bd55335ff7f288024d,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,6778b6bd55335ff7f2880691,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,6778b6be55335ff7f2880ea3,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [105]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query_2 = {'LocalAuthorityName': {'$regex': 'London'}, 'RatingValue': {'$gte': 4}}

result_2 = establishments.find(query_2)

# Use count_documents to display the number of documents in the result
print('Number of establishments in London with a rating value of 4 or more: ', establishments.count_documents(query_2))

# Convert the cursor to a list to access the documents
result_list = list(result_2)

# Check if there are any results before trying to access the first document
if result_list:
    # Display the first document in the results using pprint
    pprint(result_list[0])
else:
    print("No establishments found with a RatingValue of 4 or more.")

Number of establishments in London with a rating value of 4 or more:  33
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6778b6bb55335ff7f287f2f5'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('0.508551')},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [110]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

#set the degree search to 0.01 and set the latitude and longitude variables of Penang Flavours
degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

#search for entries with rating of 5 and latitutde+-degree_search and longitude +-degree_search
query_3 = {'RatingValue' : '5', 'geocode.latitude' : 
    {'$gte' : latitude - degree_search, '$lte' : latitude + degree_search},
    'geocode.longitude': {'$gte' : longitude - degree_search, '$lte' : longitude + degree_search}}
#sort by the hygiene scores from lowest to greatest
sort_3 =  [('scores.Hygiene', 1)]
#set a limit of 5 establishments
limit_3 = 5

result_3 = list(establishments.find(query_3).sort(sort_3).limit(limit_3))


# Print the results
print('Number of establishments: ', len(result_3))
#display top 5 establishments
pprint(result_3)

Number of establishments:  0
[]

In [107]:
# Convert result to Pandas DataFrame
df = pd.DataFrame(result_list)
print(df)

                         _id   FHRSID  ChangesByServerID  \
0   6778b6bb55335ff7f287f2f5   621707                  0
1   6778b6bc55335ff7f287f61b  1130836                  0
2   6778b6bd55335ff7f2880168   293783                  0
3   6778b6be55335ff7f2880f68  1315095                  0
4   6778b6be55335ff7f2880f69   294474                  0
5   6778b6be55335ff7f2881671   294900                  0
6   6778b6c155335ff7f288377f   293756                  0
7   6778b6c155335ff7f2883b46   878523                  0
8   6778b6c155335ff7f2883b60   293772                  0
9   6778b6c155335ff7f2883b61   294606                  0
10  6778b6c155335ff7f2883b62   295107                  0
11  6778b6c155335ff7f2883d40   294523                  0
12  6778b6c155335ff7f2883d41   294616                  0
13  6778b6c155335ff7f2883fe1  1427985                  0
14  6778b6c155335ff7f28841ec   934211                  0
15  6778b6c155335ff7f2884212  1392440                  0
16  6778b6c155335ff7f2884216   558640                  0
17  6778b6c255335ff7f28843da  1498024                  0
18  6778b6c255335ff7f2884425  1090020                  0
19  6778b6c255335ff7f2884426  1090017                  0
20  6778b6c255335ff7f2884427  1090023                  0
21  6778b6c255335ff7f2884428  1090021                  0
22  6778b6c255335ff7f2884429  1090022                  0
23  6778b6c255335ff7f288442a  1090019                  0
24  6778b6c255335ff7f288442b  1090018                  0
25  6778b6c255335ff7f288442c  1090027                  0
26  6778b6c255335ff7f288442d  1090025                  0
27  6778b6c255335ff7f288442e  1090028                  0
28  6778b6c255335ff7f288442f  1090024                  0
29  6778b6c255335ff7f2884430  1090016                  0
30  6778b6c255335ff7f2884431   293758                  0
31  6778b6c255335ff7f2884432  1090026                  0
32  6778b6c255335ff7f2884433  1450220                  0

   LocalAuthorityBusinessID                          BusinessName  \
0              PI/000025307                             Charlie's
1              PI/000034075               Mv City Cruises Erasmus
2              PI/000002614             Benfleet Motor Yacht Club
3              PI/000036464  Coombs Catering t/a The Lock and Key
4              PI/000014647              Tilbury Seafarers Centre
5              PI/000019066                            Mv Valulla
6              PI/000002538                         Tereza Joanne
7              PI/000029844                      Brick Lane Brews
8              PI/000002585         The Nuance Group (UK) Limited
9              PI/000016185                              WH Smith
10             PI/000020749                      City Bar & Grill
11             PI/000015222                            Jet Centre
12             PI/000016269                            Caffè Nero
13             PI/000037871                Mv Sunborn Yacht Hotel
14             PI/000030457                     Good Hotel London
15             PI/000037382                         La Nonna lina
16             PI/000024155             Wake Up Docklands Limited
17             PI/000038347                      MV Venus Clipper
18             PI/000033476                    MV Typhoon clipper
19             PI/000033472                       MV Moon clipper
20             PI/000033479                    MV Jupiter clipper
21             PI/000033477                    MV Monsoon clipper
22             PI/000033478                     MV Meteor clipper
23             PI/000033475                    MV Tornado clipper
24             PI/000033473                    MV Mercury clipper
25             PI/000033483                    MV Cyclone clipper
26             PI/000033481                  MV Hurricane clipper
27             PI/000033484                    MV Neptune clipper
28             PI/000033480                     MV Galaxy clipper
29             PI/000033470                        MV Sun clipper
30             PI/000002546                      Mv Storm Clipper
31             PI/000033482                     MV Aurora clipper
32             PI/000038259                       Canary Wharf 1V

                         BusinessType  BusinessTypeID  \
0             Other catering premises            7841
1             Other catering premises            7841
2             Other catering premises            7841
3             Restaurant/Cafe/Canteen               1
4             Restaurant/Cafe/Canteen               1
5             Other catering premises            7841
6             Other catering premises            7841
7             Restaurant/Cafe/Canteen               1
8                   Retailers - other            4613
9                   Retailers - other            4613
10            Restaurant/Cafe/Canteen               1
11            Restaurant/Cafe/Canteen               1
12            Restaurant/Cafe/Canteen               1
13  Hotel/bed & breakfast/guest house            7842
14            Other catering premises            7841
15            Other catering premises            7841
16            Other catering premises            7841
17            Other catering premises            7841
18            Other catering premises            7841
19            Other catering premises            7841
20            Other catering premises            7841
21            Other catering premises            7841
22            Other catering premises            7841
23            Other catering premises            7841
24            Other catering premises            7841
25            Other catering premises            7841
26            Other catering premises            7841
27            Other catering premises            7841
28            Other catering premises            7841
29            Other catering premises            7841
30            Other catering premises            7841
31            Other catering premises            7841
32            Other catering premises            7841

                                         AddressLine1  \
0          Oak Apple Farm Building 103 Sheernes Docks
1                                  Cherry Garden Pier
2                                          Ferry Road
3                                   Leslie Ford House
4                           Tenants Row Tilbury Docks
5   Reeds River Cruises LtdKings ReachRiver Thames...
6   Funcraft UK Ltd King George V Dock Woolwich Ma...
7                        Air side London City Airport
8                   Duty Free Shop Passenger Terminal
9                                 London City Airport
10                      London City Airport (Airside)
11                                London City Airport
12       London City Airport Airside Departure Lounge
13                                    Western Gateway
14                Western Gateway Royal Victoria Dock
15                                          Dock Road
16                 Western Beach Royal Victoria Docks
17                                 Trinity Buoy Wharf
18     Thames Clippers Unit 12 The Riverside Building
19             Thames Clippers 3rd flr Clippers House
20     Thames Clippers Unit 12 The Riverside Building
21     Thames Clippers Unit 12 The Riverside Building
22     Thames Clippers Unit 12 The Riverside Building
23     Thames Clippers Unit 12 The Riverside Building
24             Thames Clippers 3rd flr Clippers House
25     Thames Clippers Unit 12 The Riverside Building
26     Thames Clippers Unit 12 The Riverside Building
27     Thames Clippers Unit 12 The Riverside Building
28     Thames Clippers Unit 12 The Riverside Building
29             Thames Clippers 3rd flr Clippers House
30     Thames Clippers Unit 12 The Riverside Building
31     Thames Clippers Unit 12 The Riverside Building
32                                 Trinity Buoy Wharf

                                    AddressLine2 AddressLine3  ...  \
0                                    Sheppy Kent               ...
1               Cherry Garden Street Rotherhithe     Charlton  ...
2                           South Benfleet Essex               ...
3                                        Tilbury     Charlton  ...
4                                  Tilbury Essex               ...
5                                         London               ...
6                                         London               ...
7                                         London               ...
8           London City AirportRoyal DocksLondon               ...
9                              Silvertown London               ...
10                                        London               ...
11                            Royal Docks London               ...
12                            Royal Docks London               ...
13                           Royal Victoria Dock               ...
14  Floating Platform next to Emirates Cable Car               ...
15                                        London     Charlton  ...
16                                        London     Charlton  ...
17                                 Orchard Place               ...
18    64 Orchard Place Trinity Buoy Wharf London               ...
19       Orchard Place Trinity Buoy Wharf London               ...
20    64 Orchard Place Trinity Buoy Wharf London               ...
21    64 Orchard Place Trinity Buoy Wharf London               ...
22    64 Orchard Place Trinity Buoy Wharf London               ...
23    64 Orchard Place Trinity Buoy Wharf London               ...
24       Orchard Place Trinity Buoy Wharf London               ...
25    64 Orchard Place Trinity Buoy Wharf London               ...
26    64 Orchard Place Trinity Buoy Wharf London               ...
27    64 Orchard Place Trinity Buoy Wharf London               ...
28    64 Orchard Place Trinity Buoy Wharf London               ...
29       Orchard Place Trinity Buoy Wharf London               ...
30    64 Orchard Place Trinity Buoy Wharf London               ...
31    64 Orchard Place Trinity Buoy Wharf London               ...
32                              64 Orchard Place               ...

                                               scores SchemeType  \
0   {'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...       FHRS
1   {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
2   {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
3   {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
4   {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
5   {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
6   {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
7   {'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...       FHRS
8   {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
9   {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
10  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...       FHRS
11  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
12  {'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...       FHRS
13  {'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...       FHRS
14  {'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...       FHRS
15  {'Hygiene': 0, 'Structural': 10, 'ConfidenceIn...       FHRS
16  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
17  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
18  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
19  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
20  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
21  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
22  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
23  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
24  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
25  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
26  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
27  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
28  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
29  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
30  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
31  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS
32  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...       FHRS

                                              geocode  RightToReply  \
0      {'longitude': 0.508551, 'latitude': 51.369321}
1   {'longitude': 0.249255999922752, 'latitude': 5...
2      {'longitude': 0.561954, 'latitude': 51.543831}
3   {'longitude': 0.346336990594864, 'latitude': 5...
4      {'longitude': 0.346325, 'latitude': 51.464078}
5      {'longitude': 0.287555, 'latitude': 51.504071}
6      {'longitude': 0.069286, 'latitude': 51.501121}
7      {'longitude': 0.048006, 'latitude': 51.503733}
8      {'longitude': 0.047966, 'latitude': 51.504112}
9   {'longitude': 0.0479655750095844, 'latitude': ...
10  {'longitude': 0.0479655750095844, 'latitude': ...
11  {'longitude': 0.0405181497335434, 'latitude': ...
12     {'longitude': 0.040518, 'latitude': 51.504808}
13      {'longitude': 0.027107, 'latitude': 51.50817}
14      {'longitude': 0.01792, 'latitude': 51.507681}
15  {'longitude': 0.0157549995929003, 'latitude': ...
16     {'longitude': 0.015742, 'latitude': 51.505992}
17  {'longitude': 0.00890800673629534, 'latitude':...
18     {'longitude': 0.007816, 'latitude': 51.508259}
19  {'longitude': 0.0078159999102354, 'latitude': ...
20     {'longitude': 0.007816, 'latitude': 51.508259}
21     {'longitude': 0.007816, 'latitude': 51.508259}
22     {'longitude': 0.007816, 'latitude': 51.508259}
23     {'longitude': 0.007816, 'latitude': 51.508259}
24  {'longitude': 0.0078159999102354, 'latitude': ...
25     {'longitude': 0.007816, 'latitude': 51.508259}
26     {'longitude': 0.007816, 'latitude': 51.508259}
27     {'longitude': 0.007816, 'latitude': 51.508259}
28     {'longitude': 0.007816, 'latitude': 51.508259}
29  {'longitude': 0.0078159999102354, 'latitude': ...
30     {'longitude': 0.007816, 'latitude': 51.508259}
31     {'longitude': 0.007816, 'latitude': 51.508259}
32     {'longitude': 0.007815, 'latitude': 51.508259}

       Distance NewRatingPending  \
0   4627.439468            False
1   4627.873179            False
2   4631.968418            False
3   4636.846754            False
4   4636.847650            False
5   4640.460834            False
6   4648.301822            False
7   4649.173485            False
8   4649.188826            False
9   4649.188850            False
10  4649.188850            False
11  4649.485870            False
12  4649.485929            False
13  4650.098130            False
14  4650.415301            False
15  4650.432066            False
16  4650.432926            False
17  4650.747349            False
18  4650.805008            False
19  4650.805001            False
20  4650.805008            False
21  4650.805008            False
22  4650.805008            False
23  4650.805008            False
24  4650.805001            False
25  4650.805008            False
26  4650.805008            False
27  4650.805008            False
28  4650.805008            False
29  4650.805001            False
30  4650.805008            False
31  4650.805008            False
32  4650.805044            False

                                                 meta  \
0   {'dataSource': None, 'extractDate': '0001-01-0...
1   {'dataSource': None, 'extractDate': '0001-01-0...
2   {'dataSource': None, 'extractDate': '0001-01-0...
3   {'dataSource': None, 'extractDate': '0001-01-0...
4   {'dataSource': None, 'extractDate': '0001-01-0...
5   {'dataSource': None, 'extractDate': '0001-01-0...
6   {'dataSource': None, 'extractDate': '0001-01-0...
7   {'dataSource': None, 'extractDate': '0001-01-0...
8   {'dataSource': None, 'extractDate': '0001-01-0...
9   {'dataSource': None, 'extractDate': '0001-01-0...
10  {'dataSource': None, 'extractDate': '0001-01-0...
11  {'dataSource': None, 'extractDate': '0001-01-0...
12  {'dataSource': None, 'extractDate': '0001-01-0...
13  {'dataSource': None, 'extractDate': '0001-01-0...
14  {'dataSource': None, 'extractDate': '0001-01-0...
15  {'dataSource': None, 'extractDate': '0001-01-0...
16  {'dataSource': None, 'extractDate': '0001-01-0...
17  {'dataSource': None, 'extractDate': '0001-01-0...
18  {'dataSource': None, 'extractDate': '0001-01-0...
19  {'dataSource': None, 'extractDate': '0001-01-0...
20  {'dataSource': None, 'extractDate': '0001-01-0...
21  {'dataSource': None, 'extractDate': '0001-01-0...
22  {'dataSource': None, 'extractDate': '0001-01-0...
23  {'dataSource': None, 'extractDate': '0001-01-0...
24  {'dataSource': None, 'extractDate': '0001-01-0...
25  {'dataSource': None, 'extractDate': '0001-01-0...
26  {'dataSource': None, 'extractDate': '0001-01-0...
27  {'dataSource': None, 'extractDate': '0001-01-0...
28  {'dataSource': None, 'extractDate': '0001-01-0...
29  {'dataSource': None, 'extractDate': '0001-01-0...
30  {'dataSource': None, 'extractDate': '0001-01-0...
31  {'dataSource': None, 'extractDate': '0001-01-0...
32  {'dataSource': None, 'extractDate': '0001-01-0...

                                                links latitude longitude
0   [{'rel': 'self', 'href': 'https://api.ratings....     None      None
1   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
2   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
3   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
4   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
5   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
6   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
7   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
8   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
9   [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
10  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
11  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
12  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
13  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
14  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
15  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
16  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
17  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
18  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
19  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
20  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
21  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
22  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
23  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
24  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
25  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
26  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
27  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
28  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
29  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
30  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
31  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None
32  [{'rel': 'self', 'href': 'http://api.ratings.f...     None      None

[33 rows x 30 columns]

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [108]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match' : {'scores.Hygiene' : 0}}
# 2. Groups the matches by Local Authority and count number of documents
group_query = {'$group' : {'_id' : '$LocalAuthorityName', 'count':{'$sum':1}}}
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort' : {'count' : -1}}

#aggregation pipeline
pipeline_4 = [match_query, group_query, sort_values]
#cast pipeline results as list and save to variable
result_4 = list(establishments.aggregate(pipeline_4))

# Print the number of documents in the result
print('Number of local authority areas: ', len(result_4))
# Print the first 10 results
pprint(result_4[0:10])

Number of local authority areas:  55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [109]:
# Convert the result to a Pandas DataFrame
area_df = pd.DataFrame(result_4)
# Display the number of rows in the DataFrame
print('Number of rows in dataframe', len(area_df))
# Display the first 10 rows of the DataFrame
area_df.head(10)

Number of rows in dataframe 55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542